### ISSUE TITLE
Including init.sh in the execution of the role

### ISSUE THREAD

**Issue by gmolto** [indigo-dc/ansible-role-kepler#24]
The file docker-kepler/Dockerfile includes the following last line:
CMD /etc/init.d/vmcontext start; /home/ubuntu/init.sh
Therefore, the script init.sh, which starts up the VNC server, is only executed when a Docker container is started. 

If this role is executed on a Virtual Machine, then the script is never executed and the VNC server is not started. 

Is it possible to introduce the actions of the init.sh script inside the Ansible Role so that feature parity is matched between Docker containers and VMs?

Also, the execution of the init.sh inside a vanilla Ubuntu 14.04 Virtual Machine Image results in the following error
:...
/root/.vnc/xstartup: 25: /root/.vnc/xstartup: twm: not found
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 113 requests (113 known processed) with 0 events remaining.
Warning: This program is an suid-root program or is being run by the root user.
The full text of the error or warning message cannot be safely formatted
in this environment. You may get a more descriptive message by running the
program as a non-root user or by removing the suid bit on the executable.
xterm: Xt error: Can't open display: %s
root@vnode-0:/home/ubuntu#

**Comment by tzok** [comment]
The current version in master branch does not use `init.sh` anymore. Everything was put into the Ansible role itself.

**Comment by gmolto** [comment]
I confirm that I successfully sent [the corresponding TOSCA template](https://github.com/indigo-dc/tosca-templates/blob/master/kepler.yaml) to the Orchestrator, a VM was provisioned and fully configured and I was able to connect via VNC and start Kepler. Thank you for the work.
